-- Migration number: 0001 	 2024-03-19T07:40:29.575Z
CREATE TABLE user_account (
	id TEXT PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	email_verified BOOLEAN NOT NULL DEFAULT FALSE,
	password TEXT NOT NULL,
	user_token TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) WITHOUT ROWID;