-- Migration number: 0001
CREATE TABLE user_account (
	id TEXT PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	email_verified BOOLEAN NOT NULL DEFAULT FALSE,
	password TEXT NOT NULL,
	user_token TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) WITHOUT ROWID;